id: A97C409E8
title: 'The Magical Wish-Fulfilling Tree: A Prayer for the Long Life of His Holiness
  the Dalai Lama'
type: translation
pechas:
- I8DB88511
- ICEEC1FF7
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:53:38.354891
  last_modified_at: 2023-01-04 11:53:38.354900
  collections:
  - Fourteenth Dalai Lama Series
  - Works of Tibetan Masters
alignment_to_base:
  I8DB88511/9AA0: 161F
  ICEEC1FF7/29AD: 161F
